#! /usr/bin/env python

import os
from os import listdir
from os.path import join


home = os.path.expanduser('~')
src = "/home/traveller/vivaine/vivaine/extended-config"


def main():

    # A list of absolute paths to dotfiles we need to symlink to.
    dotfiles = get_files(src, 'dotfiles')

    for i in dotfiles:
        symlink_filename = os.path.basename(i)
        symlink_path = join(home, symlink_filename)
        make_symlink(i, symlink_path)


###############################################################################
# mini-library (this code is duplicated in link_bin_files)
###############################################################################


def make_symlink(file_name, link_name):
    try:
        os.symlink(file_name, link_name)
        print "Created symlink at %s" % link_name
    except OSError as e:
        if e.strerror == 'File exists':
            print "File exists at %s" % link_name
        else:
            print "OSError: %s" % e.strerror


def get_files(src, target):
    """
    Return a list of all the files within the directories <src>/*/<target>/
    """
    files = []

    for program in listdir(src):
        program_path = join(src, program)

        for i in listdir(program_path):
            if i == target:
                target_path = join(program_path, i)

                for j in listdir(target_path):
                    files.append(join(target_path, j))
    return files


if __name__ == '__main__':
    main()
