#! /usr/bin/env python

import os
from os import listdir
from os.path import join

home = os.path.expanduser('~')
source = "/home/traveller/config/src"

def main():
    dot_config = join(home, ".config")
    if not os.path.exists(dot_config):
        os.mkdir(dot_config)

    # Not all dotfiles are stored in /home/user
    #
    # Some are stored in /home/user/.config.
    #
    # In order to handle this we've abstracted out the symlinking
    # process so that we can makes links from ~ to all the files
    # in "dotfiles" directories and from ~/.config to all the files
    # in "configfiles" directories.
    make_links(home, "dotfiles")
    make_links(dot_config, "configfiles")

def make_links(link_dir, dir_name):
    source_files = get_files(source, dir_name)

    for i in source_files:
        make_symlink(i, join(link_dir, os.path.basename(i)))

############################################################
# mini-library (this code is duplicated in link_bin_files)
############################################################

def make_symlink(file_name, link_name):
    try:
        os.symlink(file_name, link_name)
        print "Created symlink at %s" % link_name
    except OSError as e:
        if e.strerror == 'File exists':
            print "File exists at %s" % link_name
        else:
            print "OSError: %s" % e.strerror

def get_files(src, target):
    """
    Return a list of all the files within the directories <src>/*/<target>/
    """
    files = []

    for program in listdir(src):
        program_path = join(src, program)

        for i in listdir(program_path):
            if i == target:
                target_path = join(program_path, i)

                for j in listdir(target_path):
                    files.append(join(target_path, j))
    return files

if __name__ == '__main__':
    main()
