#!/bin/sh

stow --verbose --target=/home/traveller --dir=src/emacs   dotfiles
stow --verbose --target=/home/traveller --dir=src/firefox dotfiles
stow --verbose --target=/home/traveller --dir=src/git     dotfiles
stow --verbose --target=/home/traveller --dir=src/haskell dotfiles
stow --verbose --target=/home/traveller --dir=src/mbsync  dotfiles
stow --verbose --target=/home/traveller --dir=src/msmtp   dotfiles
stow --verbose --target=/home/traveller --dir=src/mutt    dotfiles
stow --verbose --target=/home/traveller --dir=src/urxvt   dotfiles
stow --verbose --target=/home/traveller --dir=src/vim     dotfiles
stow --verbose --target=/home/traveller --dir=src/xmonad  dotfiles
