# HLint configuration file
# https://github.com/ndmitchell/hlint

- ignore: {name: "Avoid lambda"}
- ignore: {name: "Redundant do"}
- ignore: {name: "Use lambda-case"}

# From: https://gist.github.com/roman/2f6855d747457ce4c22cd64f5dc2996b
- modules:
  # - {name: Control.Arrow, within: []} # Can ban modules
  - {name: [Data.HashMap.Strict], as: HM}
  - {name: [Data.ByteString], as: BS}
  - {name: [Data.ByteString.Lazy], as: LBS}
  - {name: [Data.Text], as: T}
  - {name: [Data.Text.IO], as: TIO}

# - ignore: {name: "Use section"}
# - ignore: {name: "Use camelCase"}
# - ignore: {name: "Use list comprehension"}
# - ignore: {name: "Redundant if"}
# - ignore: {name: "Eta reduce"}
# - ignore: {name: "Parse error"}
# - ignore: {name: "Evaluate"}
# - ignore: {name: "Use &&&"}
# - ignore: {name: "Redundant compare"}

# ignore "Redundant as"
# ignore "Reduce duplication"
# ignore "Use if"
# ignore "Use import/export shortcut"
# ignore "Use infix"
# ignore "Use isNothing"
# ignore "Use section"
# ignore "Use String"
